// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7znQbuQaf12OC3jMAhsSNxj6uQzMIDFY',
    appId: '1:894154185323:web:3226a540c785c429dfef2e',
    messagingSenderId: '894154185323',
    projectId: 'chat-db2d9',
    authDomain: 'chat-db2d9.firebaseapp.com',
    storageBucket: 'chat-db2d9.firebasestorage.app',
    measurementId: 'G-ENGFVRJ087',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUE78bBQEmw2CMueZc9emiSXdpmsSXtvo',
    appId: '1:894154185323:android:80c0b63179c6718adfef2e',
    messagingSenderId: '894154185323',
    projectId: 'chat-db2d9',
    storageBucket: 'chat-db2d9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClCIwZs9DlUHBBa2oCn1q1zQ8OQ25JngQ',
    appId: '1:894154185323:ios:b809ca4fc0ed2414dfef2e',
    messagingSenderId: '894154185323',
    projectId: 'chat-db2d9',
    storageBucket: 'chat-db2d9.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClCIwZs9DlUHBBa2oCn1q1zQ8OQ25JngQ',
    appId: '1:894154185323:ios:b809ca4fc0ed2414dfef2e',
    messagingSenderId: '894154185323',
    projectId: 'chat-db2d9',
    storageBucket: 'chat-db2d9.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7znQbuQaf12OC3jMAhsSNxj6uQzMIDFY',
    appId: '1:894154185323:web:766b6202b6dfe1b4dfef2e',
    messagingSenderId: '894154185323',
    projectId: 'chat-db2d9',
    authDomain: 'chat-db2d9.firebaseapp.com',
    storageBucket: 'chat-db2d9.firebasestorage.app',
    measurementId: 'G-QBHW9L5KG7',
  );
}
